### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by wigvp** [Julian24816/IMAPFilter#1]
```
Traceback (most recent call last):
  File "/some/path/myfilter.py", line 11, in <module>
    myfilter.filter(deleteMail, _from="another@mailaddress.com")
  File "/some/path/imap_filter.py", line 291, in filter
    uid = data.split()[2][:-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
After some mails that are shown to be deleted.

Code:

```
import imap_filter, getpass

myfilter = imap_filter.IMAPSFilter("mymail@gmail.com", "Th3Pwd", "imap.gmail.com")
myfilter.select("INBOX")
def deleteMail(m):
    print("delete", m.get_internaldate())
    try:
        m.delete()
    except:
        print("[ERROR]", m)
myfilter.filter(deleteMail, _from="another@mailaddress.com")

myfilter.logout()

```

**Comment by Julian24816** [comment]
Code now raises a RuntimeError when no UID could be fetched for a message. (v1.0.2)
